#!/bin/bash
if [ -f "/usr/share/applications/mintinstall-kde.desktop" ]; then
	sed -i 's/software-properties-mint/mintinstall/g' "/usr/share/applications/mintinstall-kde.desktop"
fi
if [ -f "/usr/share/applications/system-config-printer.desktop" ]; then
	sed -i 's/NotShowIn=KDE;GNOME;/NotShowIn=GNOME;/g' "/usr/share/applications/system-config-printer.desktop"
fi
if [ -f "/usr/share/applications/ubiquity.desktop" ]; then
	sed -i '/NotShowIn=KDE;/d' "/usr/share/applications/ubiquity.desktop"
fi
if [ -f "/usr/share/applications/io.elementary.photos.desktop" ]; then
	sed -i 's/multimedia-photo-manager/shotwell/g' "/usr/share/applications/io.elementary.photos.desktop"
fi
if [ -f "/usr/share/applications/io.elementary.photos-viewer.desktop" ]; then
	sed -i 's/multimedia-photo-viewer/shotwell/g' "/usr/share/applications/io.elementary.photos-viewer.desktop"
fi
